---
EnableDefaultLinters: false
linters:
  Rubocop:
    enabled: true
    exclude:
      - "**/vendor/**/*"
      - "**/vendor/**/.*"
      - "db/**/*"
      - "node_modules/**/*"
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
