# fly.toml file generated for sofia-galvao-group on 2023-03-17T12:30:21Z

kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "mad"

[env]

[experimental]
  auto_rollback = true

[processes]
  web = "bundle exec puma -C config/puma.rb"
  worker = "bundle exec good_job start --max_threads=1"

[deploy]
  release_command = './bin/rails db:prepare:with_data'

[[services]]
  # Web service - handles HTTP traffic
  http_checks = []
  internal_port = 3000
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  # Worker service - handles background jobs
  internal_port = 4000
  processes = ["worker"]
  protocol = "tcp"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
