---
translations:
  - file: app/javascript/languages/locales.json
    patterns:
      - "*"
      - "!*.activerecord"
      - "!*.errors"
      - "!*.number.nth"
  - file: client/sofiagalvaogroup-fe/src/languages/:locale.json
    patterns:
      - "*"
