meta_product_name: "Sofia Galvão Group"
meta_title: "Sofia Galvão Group - Juntos criamos Lares Felizes!"
meta_description: "Juntos criamos Lares Felizes!"
meta_image: "banner.jpg" # should exist in `app/assets/images/`
twitter_account: "@sofiagalvaokw"   # required for Twitter Cards