meta_product_name: "Sofia Galv達o Group"
meta_title: "Sofia Galv達o Group - Together we make Happy Homes!"
meta_title_backoffice: "Backoffice | Sofia Galv達o Group"
meta_description:
  "I'm a trained marketer and value creator by passion. I worked for years with
  brands and products, in order to better serve the Client and offer him not
  only what he needed, but also what best met his aspirations. I have focused on
  people and realising their full potential, I am a Master in Neuro Linguistic
  Programming and I believe in empowering people to achieve their goals and
  realise their life purpose. I dedicated myself to the real estate sector with
  a focus on the discovery of the unique asset: the house, the client, the
  transaction, the service. At KW I found the right structure to develop the
  Sofia Galv達o Group's real estate brand with rigour, professionalism and trust.
  I have the market 'know how' and I provide my Clients the best deals, the ones
  that make them the happiest!"
meta_image: "banner_small.jpg" # should exist in `app/public/images/`
twitter_account: "@sofiagalvaokw" # required for Twitter Cards
