require: rubocop-rails
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/**/*
    - bin/*
    - config/**/*
    - node_modules/**/*
    - vendor/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/FilePath:
  Enabled: false
