# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '3.1.3'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails'

# Dotenv
gem 'dotenv-rails'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.4'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma'

# Use Redis adapter to run Action Cable in production
gem 'redis'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# API specific gems
gem 'active_model_serializers'
gem 'jbuilder'
gem 'jwt'
gem 'rack-cors'

# Other gems here
gem 'acts_as_paranoid'
gem 'carrierwave', '~> 3.0'
gem 'cloudinary', '~> 1.28'
gem 'devise'
gem 'execjs'
gem 'flipper'
gem 'flipper-active_record'
gem 'flipper-ui'
gem 'friendly_id'
gem 'friendly_id-mobility'
gem 'good_job'
gem 'listen', '~> 3.7', '>= 3.7.1'
gem 'mobility', '~> 1.2.9'
gem 'mobility-ransack', '~> 1.2.2'
gem 'money-rails', '~> 1.12'
gem 'pagy', '~> 5.10'
gem 'rails-i18n'
gem 'ransack'
gem 'sentry-rails'
gem 'sentry-ruby'

# Tests / Scrape
gem 'selenium-webdriver'
gem 'simplecov', require: false

group :development, :test do
  gem 'bullet'
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'pry'
  gem 'pry-byebug'
  gem 'rails-controller-testing'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'annotate'
  gem 'dockerfile-rails', '>= 1.2'
  gem 'erb_lint', require: false
  gem 'fabrication'
  gem 'faker'
  gem 'ruby-lsp', require: false
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara'
end

gem "sib-api-v3-sdk", "~> 9.1"
