[build]
builder = "DOCKERFILE"
dockerfilePath = "api/Dockerfile"

[deploy]
startCommand = "api/bin/rails server"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
