name: Fly Deploy
on:
  push:
    branches:
      # when you want to deploy to staging automatically, uncomment the line below
      # - staging
      - staging-disabled
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a sofia-galvao-group-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
